# Generated by Django 4.0.10 on 2023-04-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='progress_type',
            field=models.CharField(choices=[('Seconds', 'seconds'), ('minutes', 'Minutes'), ('Hours', 'hours'), ('Meters', 'meters'), ('kilometers', 'Kilometer'), ('steps', 'Steps'), ('times', 'Times')], default='times', max_length=10),
        ),
    ]
