# Generated by Django 4.0.10 on 2023-04-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalship', '0002_alter_goal_progress_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
