# Generated by Django 4.0.10 on 2023-04-07 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goalship', '0003_alter_goal_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='goal',
            name='duration',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='friends', to='goalship.profile'),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progess', to='goalship.goal'),
        ),
        migrations.AlterField(
            model_name='userreward',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_of', to='goalship.reward'),
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
