# Generated by Django 4.0.10 on 2023-04-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalship', '0004_remove_goal_end_date_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friend',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='goalship.profile'),
        ),
    ]
