# Generated by Django 4.0.10 on 2023-04-08 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalship', '0005_remove_profile_friend_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
