# Generated by Django 4.0.10 on 2023-04-17 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goalship', '0007_alter_dailyprogress_id_alter_goal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreward',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goalship.goal'),
        ),
    ]
