# Generated by Django 4.0.10 on 2023-04-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalship', '0008_userreward_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='image',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reward',
            name='image',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='progress_type',
            field=models.CharField(choices=[('Seconds', 'seconds'), ('minutes', 'Minutes'), ('Hours', 'hours'), ('Meters', 'meters'), ('kilometers', 'Kilometer'), ('steps', 'Steps'), ('times', 'Times'), ('litres', 'Litre'), ('ml', 'Ml')], default='times', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
