# Generated by Django 4.0.10 on 2023-04-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalship', '0009_goal_image_reward_image_alter_goal_progress_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='progress',
            field=models.IntegerField(default=1),
        ),
    ]
