# Generated by Django 4.0.10 on 2023-04-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalship', '0010_alter_goal_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='progress_type',
            field=models.CharField(default='times', max_length=10),
        ),
    ]
